services:
  traefik:
    image: traefik:v3.7.13@sha256:1c32e7c368204fd72812152ebdd2ac0425993df6fd982317deb02e48f2d5423c
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik_letsencrypt:/letsencrypt"
      - "./config:/etc/traefik"
    networks:
      - default
      - reverse-proxy
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=${ACME_EMAIL:?}
      - PORTAINER_HOSTNAME=${PORTAINER_HOSTNAME:?}

volumes:
  traefik_letsencrypt:

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true
