services:
  traefik:
    image: traefik:v3.7.3@sha256:25cd7b175a493ea66a40329e23a649b59eda38b7e2a570493bf63fc4d74fd1c1
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik_letsencrypt:/letsencrypt"
      - "./config:/etc/traefik"
    networks:
      - default
      - reverse-proxy
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=${ACME_EMAIL:?}
      - PORTAINER_HOSTNAME=${PORTAINER_HOSTNAME:?}

volumes:
  traefik_letsencrypt:

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true
