services:
  traefik:
    image: traefik:v3.7.5@sha256:5a52522fa05731d9c537540f873ba8c4842e83354c27275b747145bab75da120
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik_letsencrypt:/letsencrypt"
      - "./config:/etc/traefik"
    networks:
      - default
      - reverse-proxy
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=${ACME_EMAIL:?}
      - PORTAINER_HOSTNAME=${PORTAINER_HOSTNAME:?}

volumes:
  traefik_letsencrypt:

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true
